/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dave' at '8/10/16 7:59 PM' with Gradle 2.14.1
 *
 * @author dave, @date 8/10/16 7:59 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
